# Potential Field Method Gains
attractive_potential_gain: 50.0
repulsive_potential_gain: 100.0

# Lidar Data Informations
lidar_distnace_max: 10.0          # meters
lidar_distance_min: 0.5           # meters
lidar_angle_max: 1.57619449019    # radian
lidar_angle_min: -1.57619449019   # radian
lidar_data_length: 716

# Lidar Clustering Parameters
n_distance_segment: 4
clustering_threshold: 10          # meters
merging_threshold: 0.4            # meters

# Robot Dynamics Parameters
# Linear
acc_x_lim: 1.0
vel_x_max: 1.0
vel_x_min: 0.1
# Angular
acc_theta_lim: 1.0
vel_theta_max: 1.0
vel_theta_min: 0.2

# Goal Parameters
xy_goal_tolerance: 0.4
yaw_goal_tolerance: 0.1
in_place_vel_theta: 0.2